server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker_containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'log_stream'
      - source_labels: ['__meta_docker_container_label_name']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'compose_service'

  - job_name: jenkins_logs
    static_configs:
      - targets: [localhost]
        labels:
          job: jenkins_logs
          __path__: /var/lib/docker/containers/*/*-json.log

  - job_name: system_logs
    static_configs:
      - targets: [localhost]
        labels:
          job: system_logs
          __path__: /var/log/*.log

  - job_name: jenkins_specific_logs
    static_configs:
      - targets: [localhost]
        labels:
          job: jenkins_specific
          __path__: /var/jenkins_home/logs/*.log